// @generated by `cargo run -p moire-web --bin gen_frontend_types`
// Do not edit by hand.

/**
 * Response for `GET /api/source/preview`.
 */
export interface SourcePreviewResponse {
  frame_id: FrameId;
  source_file: string;
  target_line: number;
  target_col?: number;
  total_lines: number;
  /**
   * Full arborium-highlighted HTML for the entire file.
   * The frontend splits this into per-line strings using splitHighlightedHtml.
   */
  html: string;
  /**
   * Highlighted HTML for the cut scope excerpt (function/impl with cuts).
   * When present, the frontend should prefer this over windowing into `html`.
   */
  context_html?: string;
  /**
   * 1-based inclusive line range of the scope in the original file.
   * Line 1 of context_html = line context_range.start in the original.
   */
  context_range?: LineRange;
  /**
   * Single-line highlighted HTML of the target statement, whitespace-collapsed.
   * Used for compact collapsed-frame display.
   */
  context_line?: string;
}

/**
 * A 1-based inclusive line range within a source file.
 */
export interface LineRange {
  start: number;
  end: number;
}

export type FrameId = number;

export type u64 = number;

export interface RecordingImportBody {
  version: number;
  session: RecordingSessionInfo;
  frames: RecordingImportFrame[];
}

export interface RecordingImportFrame {
  frame_index: number;
  snapshot: unknown;
}

export interface RecordingSessionInfo {
  session_id: SessionId;
  status: RecordingSessionStatus;
  interval_ms: number;
  started_at_unix_ms: number;
  stopped_at_unix_ms?: number;
  frame_count: number;
  max_frames: number;
  max_memory_bytes: number;
  overflowed: boolean;
  approx_memory_bytes: number;
  avg_capture_ms: number;
  max_capture_ms: number;
  total_capture_ms: number;
  frames: FrameSummary[];
}

export interface FrameSummary {
  frame_index: number;
  captured_at_unix_ms: number;
  process_count: number;
  capture_duration_ms: number;
}

export type RecordingSessionStatus = "recording" | "stopped";

export type SessionId = string;

export type String = string;

export interface RecordCurrentResponse {
  session?: RecordingSessionInfo;
}

export interface RecordStartRequest {
  interval_ms?: number;
  max_frames?: number;
  max_memory_bytes?: number;
}

export interface SnapshotSymbolicationUpdate {
  snapshot_id: number;
  total_frames: number;
  completed_frames: number;
  done: boolean;
  updated_frames: SnapshotFrameRecord[];
}

export interface SnapshotFrameRecord {
  frame_id: FrameId;
  frame: SnapshotBacktraceFrame;
}

export type SnapshotBacktraceFrame =
  | { resolved: BacktraceFrameResolved }
  | { unresolved: BacktraceFrameUnresolved };

export interface BacktraceFrameUnresolved {
  module_path: string;
  rel_pc: RelPc;
  reason: string;
}

export type RelPc = number;

export interface BacktraceFrameResolved {
  module_path: string;
  function_name: string;
  source_file: string;
  line?: number;
}

/**
 * Top-level response for `/api/snapshot`.
 */
export interface SnapshotCutResponse {
  /**
   * Monotonic server-side snapshot id for correlating stream updates.
   */
  snapshot_id: number;
  /**
   * Wall-clock milliseconds (Unix epoch) when this cut was assembled server-side.
   */
  captured_at_unix_ms: number;
  /**
   * Processes that replied within the timeout window.
   */
  processes: ProcessSnapshotView[];
  /**
   * Processes connected at request time but timed out before response.
   */
  timed_out_processes: TimedOutProcess[];
  /**
   * Backtraces referenced by entities/scopes/edges/events in this snapshot.
   */
  backtraces: SnapshotBacktrace[];
  /**
   * Deduplicated frame catalog keyed by frame_id.
   */
  frames: SnapshotFrameRecord[];
}

export interface SnapshotBacktrace {
  backtrace_id: BacktraceId;
  frame_ids: FrameId[];
}

export type BacktraceId = number;

export interface TimedOutProcess {
  process_id: ProcessId;
  process_name: string;
  pid: number;
}

export type ProcessId = string;

/**
 * Per-process envelope inside a snapshot cut.
 */
export interface ProcessSnapshotView {
  process_id: ProcessId;
  process_name: string;
  pid: number;
  ptime_now_ms: number;
  snapshot: Snapshot;
  scope_entity_links?: ScopeEntityLink[];
}

export interface ScopeEntityLink {
  scope_id: string;
  entity_id: string;
}

/**
 * A snapshot is a point-in-time process envelope of graph state.
 */
export interface Snapshot {
  /**
   * Runtime entities present in this snapshot.
   */
  entities: Entity[];
  /**
   * Execution scopes present in this snapshot.
   */
  scopes: Scope[];
  /**
   * Entity-to-entity edges present in this snapshot.
   */
  edges: Edge[];
  /**
   * Point-in-time events captured for this snapshot.
   */
  events: Event[];
}

export interface Event {
  /**
   * Opaque event identifier.
   */
  id: EventId;
  /**
   * Event timestamp.
   */
  at: PTime;
  /**
   * Event source.
   */
  backtrace: BacktraceId;
  /**
   * Event target (entity or scope).
   */
  target: EventTarget;
  /**
   * Event kind.
   */
  kind: EventKind;
}

export type EventKind =
  | "state_changed"
  | "channel_sent"
  | "channel_received"
  | { custom: CustomEventKind };

/**
 * A user-defined event kind with arbitrary payload.
 *
 * Library consumers can emit custom events on any entity without modifying moire source.
 */
export interface CustomEventKind {
  /**
   * Event kind identifier (e.g. "query_executed").
   */
  kind: string;
  /**
   * Human-readable display name (e.g. "Query Executed").
   */
  display_name: string;
  /**
   * Arbitrary structured payload as JSON.
   */
  payload: Json;
}

export type Json = string;

export type EventTarget =
  | { entity: EntityId }
  | { scope: ScopeId };

export type ScopeId = string;

export type EntityId = string;

export type PTime = number;

export type EventId = string;

/**
 * Relationship between two entities.
 */
export interface Edge {
  /**
   * Source entity in the causal relationship.
   */
  src: EntityId;
  /**
   * Destination entity in the causal relationship.
   */
  dst: EntityId;
  /**
   * Backtrace when this edge was created
   */
  backtrace: BacktraceId;
  /**
   * Causal edge kind.
   */
  kind: EdgeKind;
}

export type EdgeKind = "polls" | "waiting_on" | "paired_with" | "holds";

/**
 * A scope groups execution context over time (for example process/thread/task/connection).
 */
export interface Scope {
  /**
   * Opaque scope identifier.
   */
  id: ScopeId;
  /**
   * When we first started tracking this scope.
   */
  birth: PTime;
  /**
   * Location in source code and crate information.
   */
  backtrace: BacktraceId;
  /**
   * Human-facing name for this scope.
   */
  name: string;
  /**
   * More specific info about the scope.
   */
  body: ScopeBody;
}

export type ScopeBody =
  | { process: ProcessScopeBody }
  | { thread: ThreadScopeBody }
  | { task: TaskScopeBody }
  | { connection: ConnectionScopeBody };

export interface ConnectionScopeBody {
  local_addr?: string;
  peer_addr?: string;
}

export interface TaskScopeBody {
  task_key: string;
}

export interface ThreadScopeBody {
  thread_name?: string;
}

export interface ProcessScopeBody {
  pid: number;
}

/**
 * A: future, a lock, a channel end (tx, rx), a connection leg, a socket, etc.
 */
export interface Entity {
  /**
   * Opaque entity identifier.
   */
  id: EntityId;
  /**
   * When we first started tracking this entity
   */
  birth: PTime;
  /**
   * When this entity was logically removed (deferred removal).
   * Present means the entity is dead but kept alive for event references.
   */
  removed_at?: PTime;
  /**
   * Backtrace when this edge was created
   */
  backtrace: BacktraceId;
  /**
   * Human-facing name for this entity.
   */
  name: string;
  /**
   * More specific info about the entity (depending on its kind)
   */
  body: EntityBody;
}

export type EntityBody =
  | { future: FutureEntity }
  | { lock: LockEntity }
  | { mpsc_tx: MpscTxEntity }
  | { mpsc_rx: MpscRxEntity }
  | { broadcast_tx: BroadcastTxEntity }
  | { broadcast_rx: BroadcastRxEntity }
  | { watch_tx: WatchTxEntity }
  | { watch_rx: WatchRxEntity }
  | { oneshot_tx: OneshotTxEntity }
  | { oneshot_rx: OneshotRxEntity }
  | { semaphore: SemaphoreEntity }
  | { notify: NotifyEntity }
  | { once_cell: OnceCellEntity }
  | { command: CommandEntity }
  | { file_op: FileOpEntity }
  | { net_connect: NetConnectEntity }
  | { net_accept: NetAcceptEntity }
  | { net_read: NetReadEntity }
  | { net_write: NetWriteEntity }
  | { request: RequestEntity }
  | { response: ResponseEntity }
  | { custom: CustomEntity }
  | { aether: AetherEntity };

/**
 * Synthetic entity for uninstrumented tasks.
 *
 * Created automatically when a moire-instrumented primitive is used from a task
 * that was not spawned via `moire::task::spawn`. Makes deadlocks in uninstrumented
 * code visible on the dashboard.
 */
export interface AetherEntity {
  /**
   * Tokio task ID that this aether represents.
   */
  task_id: string;
}

/**
 * A user-defined entity kind with arbitrary metadata.
 *
 * Library consumers can create custom entity kinds without modifying moire source.
 * All fields are user-controlled; the runtime treats them opaquely.
 */
export interface CustomEntity {
  /**
   * Canonical kind identifier (e.g. "database_pool"). snake_case, non-empty.
   */
  kind: string;
  /**
   * Human-readable display name (e.g. "Database Pool").
   */
  display_name: string;
  /**
   * Category for UI grouping ("async"/"sync"/"channel"/"rpc"/"net"/"fs"/"time"/"meta").
   */
  category: string;
  /**
   * Phosphor icon name (e.g. "Database", "Cpu"). Empty string = default icon.
   */
  icon: string;
  /**
   * Arbitrary structured metadata as a JSON object string.
   */
  attrs: Json;
}

export interface ResponseEntity {
  /**
   * Service name portion of the RPC endpoint.
   */
  service_name: string;
  /**
   * Method name portion of the RPC endpoint.
   */
  method_name: string;
  /**
   * Response status and payload/error details.
   */
  status: ResponseStatus;
}

export type ResponseStatus =
  | "pending"
  | { ok: Json }
  | { error: ResponseError }
  | "cancelled";

export type ResponseError =
  | { internal: string }
  | { user_json: Json };

/**
 * Correlation token for RPC is the request entity id propagated in metadata.
 * The receiver generates a fresh response entity id and emits `request -> response`.
 */
export interface RequestEntity {
  /**
   * Service name portion of the RPC endpoint.
   *
   * Example: for `vfs.lookupItem`, this is `vfs`.
   */
  service_name: string;
  /**
   * Method name portion of the RPC endpoint.
   *
   * Example: for `vfs.lookupItem`, this is `lookupItem`.
   */
  method_name: string;
  /**
   * JSON-encoded request arguments.
   *
   * This is always valid JSON and should be `[]` when the method has no args.
   */
  args_json: Json;
}

export interface NetWriteEntity {
  /**
   * Endpoint address string (for example `127.0.0.1:8080`).
   */
  addr: string;
}

export interface NetReadEntity {
  /**
   * Endpoint address string (for example `127.0.0.1:8080`).
   */
  addr: string;
}

export interface NetAcceptEntity {
  /**
   * Endpoint address string (for example `127.0.0.1:8080`).
   */
  addr: string;
}

export interface NetConnectEntity {
  /**
   * Endpoint address string (for example `127.0.0.1:8080`).
   */
  addr: string;
}

export interface FileOpEntity {
  /**
   * File operation type.
   */
  op: FileOpKind;
  /**
   * Absolute or process-relative file path.
   */
  path: string;
}

export type FileOpKind = "open" | "read" | "write" | "sync" | "metadata" | "remove" | "rename" | "other";

export interface CommandEntity {
  /**
   * Executable path or program name.
   */
  program: string;
  /**
   * Command-line arguments.
   */
  args: string[];
  /**
   * Environment entries in `KEY=VALUE` form.
   */
  env: string[];
}

export interface OnceCellEntity {
  /**
   * Number of tasks currently waiting for initialization.
   */
  waiter_count: number;
  /**
   * Current once-cell lifecycle state.
   */
  state: OnceCellState;
}

export type OnceCellState = "empty" | "initializing" | "initialized";

export interface NotifyEntity {
  /**
   * Number of tasks currently waiting on this notify.
   */
  waiter_count: number;
}

export interface SemaphoreEntity {
  /**
   * Total permits configured for this semaphore.
   */
  max_permits: number;
  /**
   * Current number of permits acquired and not yet released.
   */
  handed_out_permits: number;
}

export type OneshotRxEntity = object;

export interface OneshotTxEntity {
  sent: boolean;
}

export type WatchRxEntity = object;

export interface WatchTxEntity {
  last_update_at?: PTime;
}

export interface BroadcastRxEntity {
  lag: number;
}

export interface BroadcastTxEntity {
  capacity: number;
}

export type MpscRxEntity = object;

export interface MpscTxEntity {
  /**
   * Current queue length.
   */
  queue_len: number;
  /**
   * Configured capacity (`None` for unbounded).
   */
  capacity?: number;
}

export interface LockEntity {
  /**
   * Kind of lock primitive.
   */
  kind: LockKind;
}

export type LockKind = "mutex" | "rw_lock" | "other";

export type FutureEntity = object;

export interface SqlResponse {
  columns: string[];
  rows: unknown[];
  row_count: number;
}

export interface QueryRequest {
  name: string;
  limit?: number;
}

export interface SqlRequest {
  sql: string;
}

export interface ApiError {
  error: string;
}

export interface CutStatusResponse {
  cut_id: CutId;
  requested_at_ns: number;
  pending_connections: number;
  acked_connections: number;
  pending_conn_ids: ConnectionId[];
}

export type ConnectionId = number;

export type CutId = string;

export interface TriggerCutResponse {
  cut_id: CutId;
  requested_at_ns: number;
  requested_connections: number;
}

export interface ConnectedProcessInfo {
  conn_id: ConnectionId;
  process_id: ProcessId;
  process_name: string;
  pid: number;
}

/**
 * API response for connected processes.
 */
export interface ConnectionsResponse {
  connected_processes: number;
  processes: ConnectedProcessInfo[];
}

