// @generated by `cargo run -p moire-web --bin gen_frontend_types`
// Do not edit by hand.
// f[impl types.gen.source]
// f[impl types.gen.tool]
// f[impl types.gen.header]

export interface RecordingImportBody {
  version: number;
  session: RecordingSessionInfo;
  frames: RecordingImportFrame[];
}

export interface RecordingImportFrame {
  frame_index: number;
  snapshot: unknown;
}

export interface RecordingSessionInfo {
  session_id: string;
  status: RecordingSessionStatus;
  interval_ms: number;
  started_at_unix_ms: number;
  stopped_at_unix_ms?: number;
  frame_count: number;
  max_frames: number;
  max_memory_bytes: number;
  overflowed: boolean;
  approx_memory_bytes: number;
  avg_capture_ms: number;
  max_capture_ms: number;
  total_capture_ms: number;
  frames: FrameSummary[];
}

export interface FrameSummary {
  frame_index: number;
  captured_at_unix_ms: number;
  process_count: number;
  capture_duration_ms: number;
}

export type RecordingSessionStatus = "recording" | "stopped";

export interface RecordCurrentResponse {
  session?: RecordingSessionInfo;
}

export interface RecordStartRequest {
  interval_ms?: number;
  max_frames?: number;
  max_memory_bytes?: number;
}

/**
 * Top-level response for `/api/snapshot`.
 */
export interface SnapshotCutResponse {
  /**
   * Wall-clock milliseconds (Unix epoch) when this cut was assembled server-side.
   */
  captured_at_unix_ms: number;
  /**
   * Processes that replied within the timeout window.
   */
  processes: ProcessSnapshotView[];
  /**
   * Processes connected at request time but timed out before response.
   */
  timed_out_processes: TimedOutProcess[];
}

export interface TimedOutProcess {
  process_id: number;
  process_name: string;
  pid: number;
}

/**
 * Per-process envelope inside a snapshot cut.
 */
export interface ProcessSnapshotView {
  process_id: number;
  process_name: string;
  pid: number;
  ptime_now_ms: number;
  snapshot: Snapshot;
  scope_entity_links?: ScopeEntityLink[];
}

export interface ScopeEntityLink {
  scope_id: string;
  entity_id: string;
}

/**
 * A snapshot is a point-in-time process envelope of graph state.
 */
export interface Snapshot {
  /**
   * Resolved source table for every `SourceId` referenced in this snapshot.
   */
  sources: SnapshotSource[];
  /**
   * Runtime entities present in this snapshot.
   */
  entities: Entity[];
  /**
   * Execution scopes present in this snapshot.
   */
  scopes: Scope[];
  /**
   * Entity-to-entity edges present in this snapshot.
   */
  edges: Edge[];
  /**
   * Point-in-time events captured for this snapshot.
   */
  events: Event[];
}

export interface Event {
  /**
   * Opaque event identifier.
   */
  id: EventId;
  /**
   * Event timestamp.
   */
  at: PTime;
  /**
   * Event source.
   */
  source: SourceId;
  /**
   * Event target (entity or scope).
   */
  target: EventTarget;
  /**
   * Event kind.
   */
  kind: EventKind;
}

export type EventKind = "state_changed" | "channel_sent" | "channel_received";

export type EventTarget = { entity: EntityId } | { scope: ScopeId };

export type ScopeId = string;

export type String = string;

export type EntityId = string;

export type SourceId = number;

export type u64 = number;

export type PTime = number;

export type EventId = string;

/**
 * Relationship between two entities.
 */
export interface Edge {
  /**
   * Source entity in the causal relationship.
   */
  src: EntityId;
  /**
   * Destination entity in the causal relationship.
   */
  dst: EntityId;
  /**
   * Location in source code and crate information.
   */
  source: SourceId;
  /**
   * Causal edge kind.
   */
  kind: EdgeKind;
}

export type EdgeKind = "polls" | "waiting_on" | "paired_with" | "holds";

/**
 * A scope groups execution context over time (for example process/thread/task/connection).
 */
export interface Scope {
  /**
   * Opaque scope identifier.
   */
  id: ScopeId;
  /**
   * When we first started tracking this scope.
   */
  birth: PTime;
  /**
   * Location in source code and crate information.
   */
  source: SourceId;
  /**
   * Human-facing name for this scope.
   */
  name: string;
  /**
   * More specific info about the scope.
   */
  body: ScopeBody;
}

export type ScopeBody =
  | { process: ProcessScopeBody }
  | { thread: ThreadScopeBody }
  | { task: TaskScopeBody }
  | { connection: ConnectionScopeBody };

export interface ConnectionScopeBody {
  local_addr?: string;
  peer_addr?: string;
}

export interface TaskScopeBody {
  task_key: string;
}

export interface ThreadScopeBody {
  thread_name?: string;
}

export interface ProcessScopeBody {
  pid: number;
}

/**
 * A: future, a lock, a channel end (tx, rx), a connection leg, a socket, etc.
 */
export interface Entity {
  /**
   * Opaque entity identifier.
   */
  id: EntityId;
  /**
   * When we first started tracking this entity
   */
  birth: PTime;
  /**
   * Location in source code and crate information.
   */
  source: SourceId;
  /**
   * Human-facing name for this entity.
   */
  name: string;
  /**
   * More specific info about the entity (depending on its kind)
   */
  body: EntityBody;
}

export type EntityBody =
  | { future: FutureEntity }
  | { lock: LockEntity }
  | { mpsc_tx: MpscTxEntity }
  | { mpsc_rx: MpscRxEntity }
  | { broadcast_tx: BroadcastTxEntity }
  | { broadcast_rx: BroadcastRxEntity }
  | { watch_tx: WatchTxEntity }
  | { watch_rx: WatchRxEntity }
  | { oneshot_tx: OneshotTxEntity }
  | { oneshot_rx: OneshotRxEntity }
  | { semaphore: SemaphoreEntity }
  | { notify: NotifyEntity }
  | { once_cell: OnceCellEntity }
  | { command: CommandEntity }
  | { file_op: FileOpEntity }
  | { net_connect: NetEntity }
  | { net_accept: NetEntity }
  | { net_read: NetEntity }
  | { net_write: NetEntity }
  | { request: RequestEntity }
  | { response: ResponseEntity };

export interface ResponseEntity {
  /**
   * Service name portion of the RPC endpoint.
   */
  service_name: string;
  /**
   * Method name portion of the RPC endpoint.
   */
  method_name: string;
  /**
   * Response status and payload/error details.
   */
  status: ResponseStatus;
}

export type ResponseStatus =
  | { pending: "pending" }
  | { ok: Json }
  | { error: ResponseError }
  | { cancelled: "cancelled" };

export type ResponseError = { internal: string } | { user_json: Json };

export type Json = string;

/**
 * Correlation token for RPC is the request entity id propagated in metadata.
 * The receiver generates a fresh response entity id and emits `request -> response`.
 */
export interface RequestEntity {
  /**
   * Service name portion of the RPC endpoint.
   *
   * Example: for `vfs.lookupItem`, this is `vfs`.
   */
  service_name: string;
  /**
   * Method name portion of the RPC endpoint.
   *
   * Example: for `vfs.lookupItem`, this is `lookupItem`.
   */
  method_name: string;
  /**
   * JSON-encoded request arguments.
   *
   * This is always valid JSON and should be `[]` when the method has no args.
   */
  args_json: Json;
}

export interface NetEntity {
  /**
   * Endpoint address string (for example `127.0.0.1:8080`).
   */
  addr: string;
}

export interface FileOpEntity {
  /**
   * File operation type.
   */
  op: FileOpKind;
  /**
   * Absolute or process-relative file path.
   */
  path: string;
}

export type FileOpKind =
  | "open"
  | "read"
  | "write"
  | "sync"
  | "metadata"
  | "remove"
  | "rename"
  | "other";

export interface CommandEntity {
  /**
   * Executable path or program name.
   */
  program: string;
  /**
   * Command-line arguments.
   */
  args: string[];
  /**
   * Environment entries in `KEY=VALUE` form.
   */
  env: string[];
}

export interface OnceCellEntity {
  /**
   * Number of tasks currently waiting for initialization.
   */
  waiter_count: number;
  /**
   * Current once-cell lifecycle state.
   */
  state: OnceCellState;
}

export type OnceCellState = "empty" | "initializing" | "initialized";

export interface NotifyEntity {
  /**
   * Number of tasks currently waiting on this notify.
   */
  waiter_count: number;
}

export interface SemaphoreEntity {
  /**
   * Total permits configured for this semaphore.
   */
  max_permits: number;
  /**
   * Current number of permits acquired and not yet released.
   */
  handed_out_permits: number;
}

export type OneshotRxEntity = object;

export interface OneshotTxEntity {
  sent: boolean;
}

export type WatchRxEntity = object;

export interface WatchTxEntity {
  last_update_at?: PTime;
}

export interface BroadcastRxEntity {
  lag: number;
}

export interface BroadcastTxEntity {
  capacity: number;
}

export type MpscRxEntity = object;

export interface MpscTxEntity {
  /**
   * Current queue length.
   */
  queue_len: number;
  /**
   * Configured capacity (`None` for unbounded).
   */
  capacity?: number;
}

export interface LockEntity {
  /**
   * Kind of lock primitive.
   */
  kind: LockKind;
}

export type LockKind = "mutex" | "rw_lock" | "other";

export type FutureEntity = object;

/**
 * A resolved source mapping entry for interned source IDs referenced in a snapshot.
 */
export interface SnapshotSource {
  /**
   * Interned source identifier referenced by entities/scopes/edges/events.
   */
  id: SourceId;
  /**
   * Absolute UTF-8 path to the source file.
   */
  path: string;
  /**
   * 1-based source line.
   */
  line: number;
  /**
   * Crate name owning this source location.
   */
  krate: string;
}

export interface SqlResponse {
  columns: string[];
  rows: unknown[];
  row_count: number;
}

export interface QueryRequest {
  name: string;
  limit?: number;
}

export interface SqlRequest {
  sql: string;
}

export interface ApiError {
  error: string;
}

export interface CutStatusResponse {
  cut_id: string;
  requested_at_ns: number;
  pending_connections: number;
  acked_connections: number;
  pending_conn_ids: number[];
}

export interface TriggerCutResponse {
  cut_id: string;
  requested_at_ns: number;
  requested_connections: number;
}

export interface ConnectedProcessInfo {
  conn_id: number;
  process_name: string;
  pid: number;
}

/**
 * API response for connected processes.
 */
export interface ConnectionsResponse {
  connected_processes: number;
  processes: ConnectedProcessInfo[];
}
